exports.PORTALS = [
  "Upwork",
  "Fiverr",
  "Freelancer",
  "Toptal",
  "Guru",
  "PeoplePerHour",
  "SimplyHired",
  "FlexJobs",
  "99designs",
  "TaskRabbit",
  "CrowdSPRING",
  "DesignCrowd",
  "Freelance Writing Gigs",
  "We Work Remotely",
  "Remote.co",
  "Hirable",
  "SolidGigs",
  "Hubstaff Talent",
  "Codeable.io",
  "ServiceScape",
];

// exports.BID_STATUS = [
//   "Submitted",
//   "Response Received",
//   "Rejected",
//   "Accepted",
// ];

exports.BID_STATUS = {
  Submitted: "Submitted",
  Responded: "Response Received",
  Scrapped: "Scrapped",
  Converted: "Converted",
};

exports.FULL_STACK_SKILLS = [
  // Front-End
  "HTML",
  "CSS",
  "Bootstrap",
  "Tailwind CSS",
  "Bulma",
  "JavaScript",
  "React",
  "Angular",
  "Vue.js",
  "Svelte",
  "TypeScript",
  "Responsive Design",
  "Media Queries",
  "Flexbox",
  "Grid",

  // Back-End
  "Node.js",
  "Express",
  "Koa",
  "NestJS",
  "Python",
  "Django",
  "Flask",
  "FastAPI",
  "Ruby",
  "Ruby on Rails",
  "PHP",
  "Laravel",
  "Symfony",
  "Java",
  "Spring Boot",
  "JavaServer Faces (JSF)",
  "C#",
  "ASP.NET Core",
  "Go (Golang)",
  "Rust",

  // Databases
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "Microsoft SQL Server",
  "MongoDB",
  "Cassandra",
  "Redis",
  "CouchDB",
  "Neo4j",
  "ArangoDB",

  // DevOps and Deployment
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Jenkins",
  "CircleCI",
  "Travis CI",
  "GitHub Actions",
  "Docker",
  "Kubernetes",
  "AWS",
  "Google Cloud Platform (GCP)",
  "Microsoft Azure",
  "Nginx",
  "Apache",
  "Terraform",
  "Ansible",
  "CloudFormation",

  // Development Tools
  "Visual Studio Code",
  "IntelliJ IDEA",
  "Sublime Text",
  "Atom",
  "npm",
  "yarn",
  "pip",
  "gem",
  "composer",
  "Jest",
  "Mocha",
  "PyTest",
  "RSpec",
  "PHPUnit",

  // Other Essential Skills
  "RESTful Services",
  "GraphQL",
  "OAuth",
  "JWT (JSON Web Tokens)",
  "OpenID Connect",
  "HTTPS",
  "CORS",
  "OWASP Guidelines",
  "Code splitting",
  "Lazy loading",
  "Caching strategies",

  // Design and User Experience
  "UI/UX Design",
  "Figma",
  "Sketch",
  "Adobe XD",
  "Prototyping",
  "Wireframing",
  "Balsamiq",
  "InVision",
  "Axure",

  // Collaboration and Project Management
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "Jira",
  "Trello",
  "Asana",

  // Monitoring and Analytics
  "New Relic",
  "Datadog",
  "ELK Stack (Elasticsearch, Logstash, Kibana)",
  "Splunk",
  "Google Analytics",
  "Mixpanel",

  // Technology Stacks
  "MERN (MongoDB, Express, React, Node.js)",
  "MEAN (MongoDB, Express, Angular, Node.js)",
  "LAMP (Linux, Apache, MySQL, PHP)",
  "LEMP (Linux, Nginx, MySQL/MariaDB, PHP/Python/Perl)",
  "JAMstack (JavaScript, APIs, Markup)",
  "Ruby on Rails Stack",
  "Django Stack",
  "Spring Boot Stack",
  "ASP.NET Core Stack",
];
